### ISSUE TITLE
PHP notice

### ISSUE THREAD

**Issue by Spreeuw** [studioespresso/wp-sponsors#15]
I got this after updating the plugin to 2.4.1:
`
Notice: Undefined index: wp_sponsor_link_behaviour  in /wp-content/plugins/wp-sponsors/includes/class-wp-sponsors.php on line 334 
`
https://github.com/studioespresso/wp-sponsors/blob/master/includes/class-wp-sponsors.php#L334

There's a check for the other `$_POST` values but not `wp_sponsor_link_behaviour`

quick fix:
``` php
$link_behaviour = isset($_POST['wp_sponsor_link_behaviour']) ? '1' : '0';
```

**Comment by janhenckens** [comment]
Fixed in the today's update.
